### ISSUE TITLE
1.9.1.1 sample data

### ISSUE THREAD

**Issue by ollyboy** [mercator/mercator#14]
Latest git pull on AWS server with HHVM, redis.
Loaded in the 1.9.1.1 sample data
- had to disable  Unirgy_Giftcert 
- top nav on webcomm/magento-boilerplate disappeared. your boilerplate is way behind so changed the composer to get the latest. this clashed with  JR_CleverCms and I had to disable it
- the madison island theme is complaining about missing jquery ( havent had a good look yet )

I like this project happy to do some more testing.

**Comment by ollyboy** [comment]
Any chance that we could see some fixes for the above. Also is mercator going to be updated to magento 1.9.1.2 ??

**Comment by chnorton** [comment]
We're certainly planning to update to 1.9.2.0 - we've been tracking Magento versions since 1.8 and it's normally just a matter of finding some time to merge the upstream changes. The relevant security patches that were included in 1.9.2.0 have already been applied.

As for the other problems you ran into, would you be able to provide more detail about the errors you were seeing? Why did you have to disable Unirgy_Giftcert, and were you seeing errors when Magento Boilerplate clashed with CleverCMS?

**Comment by ollyboy** [comment]
Giftcert was working ok but I got php exceptions after loading in the sample data set. I will try to re-enable.

After loading in the sample data top nav stopped working in Webcomm and madison island theme ( but was working in standard magento theme ) I changed composer to get latest webcomm theme and site stopped working with following error. Disabled Clever CMS and all came back good.

2015-07-17T06:55:50+00:00 ERR (3): 
Mage_Core_Exception: message 'Invalid block type: Webcomm_BootstrapNavigation_Block_Page_Html_Topmenu', code '0' in /var/www/mercator/app/Mage.php:595
#0 /var/www/mercator/app/code/core/Mage/Core/Model/Layout.php(495): Mage->throwException('Invalid block type: Webcomm_BootstrapNavigation_Block_Page_Html_Topmenu')
#1 /var/www/mercator/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('page/html_topmenu', Array)
#2 /var/www/mercator/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('page/html_topmenu', 'catalog.topnav')
#3 /var/www/mercator/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('page/html_topmenu', 'catalog.topnav')
#4 /var/www/mercator/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Mage_Core_Model_Layout_Element, Mage_Core_Model_Layout_Element)
#5 /var/www/mercator/app/code/core/Mage/Core/Model/Layout.php(206): Mage_Core_Model_Layout->generateBlocks(Mage_Core_Model_Layout_Element)
#6 /var/www/mercator/app/code/core/Mage/Core/Model/Layout.php(206): Mage_Core_Model_Layout->generateBlocks(Mage_Core_Model_Layout_Element)
#7 /var/www/mercator/app/code/core/Mage/Core/Model/Layout.php(206): Mage_Core_Model_Layout->generateBlocks(Mage_Core_Model_Layout_Element)
#8 /var/www/mercator/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#9 /var/www/mercator/app/code/core/Mage/Cms/Helper/Page.php(113): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#10 /var/www/mercator/app/code/core/Mage/Cms/Helper/Page.php(52): Mage_Cms_Helper_Page->_renderPage(JR_CleverCms_Cms_IndexController, '1')
#11 /var/www/mercator/vendor/mercator/magento-clever-cms/app/code/community/JR/CleverCms/Helper/Cms/Page.php(13): Mage_Cms_Helper_Page->renderPage(JR_CleverCms_Cms_IndexController, '1')
#12 /var/www/mercator/app/code/core/Mage/Cms/controllers/IndexController.php(75): JR_CleverCms_Helper_Cms_Page->renderPage(JR_CleverCms_Cms_IndexController, '1')
#13 /var/www/mercator/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Cms_IndexController->noRouteAction()
#14 /var/www/mercator/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('noRoute')
#15 /var/www/mercator/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Mage_Core_Controller_Request_Http)
#16 /var/www/mercator/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#17 /var/www/mercator/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#18 /var/www/mercator/public/index.php(87): Mage->run('default', 'store')

**Comment by chnorton** [comment]
Thanks for that, gives us more to go on. Certainly appreciate you doing more testing!

**Comment by ollyboy** [comment]
did a composer remove and re-install of unirgy_giftcert. no improvement, still breaks the site with sample data loaded
